FROM alpine:latest

RUN apk update && \
	wget https://dl.google.com/go/go1.10.3.linux-amd64.tar.gz && \
	tar -C /usr/local -xvzf go1.10.3.linux-amd64.tar.gz && \
	rm go1.10.3.linux-amd64.tar.gz && \
	mkdir ~/go

COPY profile /root/.profile

WORKDIR /root
RUN source ~/.profile && \
	wget https://github.com/jcabmora/minibank/archive/week1.tar.gz -O - | tar zxf - --strip-components=2 -C go && \
	cd $GOPATH && go get -t minibank
